name: my_first_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.0+1

  flutter_facebook_login:
    git:
      url: https://github.com/roughike/flutter_facebook_login
      ref: e69fef3

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.7.3"

flutter_icons:
  android: true
  ios: true
  image_path: "assets/img/icon.jpg"

flutter:
  uses-material-design: true
